permalink: /:year/:title

collections:
  archives:
    output: true
  projects:
    output: true
    _hide_content: true
    
    
defaults:
  - scope:
      path: ""
      type: "archive"
    values:
      layout: "archive"
  - scope:
      path: ""
      type: "project"
    values:
      layout: "gallery"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

_options:
  content:
    blockquote: true 
    horizontalrule: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    bold: true
    italic: true
    numberedlist: true
    code: true
    table: true
    right: align-to-right
    center: align-to-center
    left: align-to-left
    embed: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    subscript: true
    superscript: true
    image: true
    bulletedlist: true
    styles: /assets/editor.css
